name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Update Ubuntu
      run: sudo apt-get update
    
      
    - name: Prepare X11-devs
      run: sudo apt-get install libx11-dev
      
    - name: Prepare X11-cursor
      run: sudo apt-get install libxcursor-dev
       
    - name: Prepare X11-randr
      run: sudo apt-get install libxrandr-dev
      
    - name: Prepare X11-input
      run: sudo apt-get install libxi-dev
      
    - name: Prepare X11-xinerama
      run: sudo apt-get install libxinerama-dev
      
    - name: Prepare OpenGL api
      run: sudo apt-get install libgl1-mesa-dev

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...
